language: java

jdk:
  - openjdk7
  - oraclejdk7

before_install:
  - travis_retry wget -c https://protobuf.googlecode.com/files/protobuf-2.5.0.tar.bz2
  - tar -xjf protobuf-2.5.0.tar.bz2
  - cd protobuf-2.5.0
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..

install:
  - mvn package
  - mvn assembly:assembly
